### ISSUE TITLE
Atto in Moodle 3.1 doesn´t recognize \ce

### ISSUE THREAD

**Issue by tinjaca** [geoffrowland/moodle-editor_atto-chemistry#6]

**Comment by geoffrowland** [comment]
Working for me with Moodle 3.1.

 e.g. \( \ce{H2SO4} \) displays with appropriate subscripts

Have you added the configuration to load the mhchem extension to the MathJax and/or TeX filters - depending on which of these you are using to display TeX (MathJax is the default)?

In Site Adminitration > Plugins Filters > MathJax > MathJax configuration
You need something like:
```
MathJax.Hub.Config({
    config: ["Accessible.js", "Safe.js"],
    TeX: { 
        extensions: ["mhchem.js"] 
    },
    errorSettings: { message: ["!"] },
    skipStartupTypeset: true,
    messageStyle: "none"
});
```
or in Site administration > Plugins > Filters > TeX notation > LaTeX preamble
You will need something like:
```
\usepackage[latin1]{inputenc}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage[version=4]{mhchem}
\RequirePackage{amsmath,amssymb,latexsym}
```
In the second case, you will also need to have LaTeX and the relevant extensions, including mhchem, installed on your Moodle server.

Hope that helps. Let me know if it works and I'll close the issue. Otherwise, get back to me if you still have issues and I'll try to diagnose  ;-)

**Comment by tinjaca** [comment]
Thank you very much for your help Mr. Rowland.
I had to configure both of them, MathJax and TeX. And now it works fine.
When I tryed using the configuration for TeX extensions proposed in
atto_chemistry, besides the \ce were not recognized, the atto´s toolbar
disappeared.
Once again,
Thak you

2016-05-26 10:50 GMT-05:00 Geoff Rowland <notifications@github.com>:

**Comment by geoffrowland** [comment]
Good! Glad it is now working for you. 

I usually just use MathJax, partly because it can be tricky setting up the server-side LaTeX support for Moodle and also because it is relatively easy to set up MathJax (with mhchem) for some of the other platforms, e.g. Wordpress and Mahara, that I use alongside Moodle. It is nice to have consistent, cross-platform support for maths and chemistry using MathJax.
